New log file opened at Wed Aug 19 08:24:34 EDT 2015 by 5348@JSnow-7-PC
Taking next connection to: 57027
New client attempting to connect on port: 57028-57027
  Address = /172.16.1.139:57027
This client on port 57028 has uuid 4011358e-edf7-4d5d-8e31-dff6f91966f8 configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-4011358e-edf7-4d5d-8e31-dff6f91966f8
Taking next connection to: 57027
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 57027
New client attempting to connect on port: 57250-57027
  Address = /172.16.1.139:57027
Handshake exception on socket: 57250
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 57027
New client attempting to connect on port: 57251-57027
  Address = /172.16.1.139:57027
This client on port 57251 has uuid b1aa4200-a916-4da5-8034-4f026fcd883f configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-4011358e-edf7-4d5d-8e31-dff6f91966f8, play-fork-run-b1aa4200-a916-4da5-8034-4f026fcd883f
Taking next connection to: 57027
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 57027
